### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by nouret** [maltejur/discord-screenaudio#178]
System: 
```
Operating System: Ubuntu 20.04.6 LTS
Kernel: Linux 5.15.0-83-generic
Architecture: x86-64
```

error when I try to run:
```
flatpak run de.shorsh.discord-screenaudio
Gtk-Message: 02:27:47.128: Failed to load module "canberra-gtk-module"
Gtk-Message: 02:27:47.129: Failed to load module "canberra-gtk-module"
qt.qpa.qgnomeplatform: Could not find color scheme  ""
Qt: Session management error: Could not open network socket
```

I install `sudo apt-get install libcanberra-gtk-*` , but it doesn't help.

**Comment by nouret** [comment]
I think the main problem is that I try to do it on Ubuntu 20.04. I tryed to build ot, but using Qt5 (I think  no Qt6 on ubuntu 20.04)
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index e419a7f..5f8de5d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -72,7 +72,7 @@ add_subdirectory(submodules/rohrkabel EXCLUDE_FROM_ALL)
 
 add_executable(discord-screenaudio ${discord-screenaudio_SRC})
 
-target_link_libraries(discord-screenaudio Qt::Widgets Qt::WebEngineWidgets rohrkabel)
+target_link_libraries(discord-screenaudio Qt5::Widgets Qt5::WebEngineWidgets rohrkabel)
 
 if(KF5Notifications_FOUND)
   target_link_libraries(discord-screenaudio KF5::Notifications)

```

but it doesn't build

```
[ 90%] Building CXX object CMakeFiles/discord-screenaudio.dir/src/userscript.cpp.o
/home/nouret/discord-screenaudio/src/userscript.cpp: In member function ‘void UserScript::setupHelpMenu()’:
/home/nouret/discord-screenaudio/src/userscript.cpp:45:13: error: ‘class KAboutData’ has no member named ‘addComponent’
   45 |   aboutData.addComponent("Rohrkabel", "A C++ RAII Pipewire-API Wrapper", "1.3",
      |             ^~~~~~~~~~~~
/home/nouret/discord-screenaudio/src/userscript.cpp:47:13: error: ‘class KAboutData’ has no member named ‘addComponent’
   47 |   aboutData.addComponent("arRPC",
      |             ^~~~~~~~~~~~

```

**Comment by nouret** [comment]
doesn't work, too old KDE. So, can't build on 20.04.
